class_name ActionReasons
extends RefCounted

## Player-facing pilot reasons.
const UNIT_CANNOT_TRAIN := &"UNIT_CANNOT_TRAIN"
const MUTATION_CAPACITY_FULL := &"MUTATION_CAPACITY_FULL"
const FERTILIZER_CAPACITY_FULL := &"FERTILIZER_CAPACITY_FULL"
const NOT_ENOUGH_BIOMASS := &"NOT_ENOUGH_BIOMASS"

## Stable rule reasons that are not part of the first presentation rollout.
const PLOT_STATE_REJECTS_MUTATION := &"PLOT_STATE_REJECTS_MUTATION"
const INVALID_MUTATION := &"INVALID_MUTATION"
const PLOT_STATE_REJECTS_FERTILIZER := &"PLOT_STATE_REJECTS_FERTILIZER"
const NORMIFIER_REQUIRES_MUTATION := &"NORMIFIER_REQUIRES_MUTATION"
